<?php
return [
    'default' => 'globalinduprod',
    'tenants' => [
        'globalinduprod' => [
            'domains' => [
                'globalinduprod.com',
                'www.globalinduprod.com',
            ],
            'language_code' => 'es',
            'locale' => 'es_VE',
            'admin_db' => [
                'host' => 'localhost',
                'username' => 'u680460687_globalinduprod',
                'password' => 'B1S:N8:kW',
                'database' => 'u680460687_globalinduprod',
                'port' => 3306,
                'charset' => 'utf8mb4',
            ],
            'storage' => [
                'relative_root' => 'uploads',
            ],
            'labels' => [
                'tenant.name' => 'Global Induprod',
            ],
        ],
        'globalinduprodinternational' => [
            'domains' => [
                'globalinduprodinternational.com',
                'www.globalinduprodinternational.com',
            ],
            'language_code' => 'en',
            'locale' => 'en_US',
            'admin_db' => [
                'host' => 'localhost',
                'username' => 'u680460687_globaleeuu',
                'password' => 'n5h*&BBR1K@',
                'database' => 'u680460687_globaleeuu',
                'port' => 3306,
                'charset' => 'utf8mb4',
            ],
            'storage' => [
                'relative_root' => 'uploads/international',
            ],
            'labels' => [
                'tenant.name' => 'Global Induprod International',
                'header.nav.home' => 'Home',
                'header.nav.about' => 'About Us',
                'header.nav.services' => 'Services',
                'header.nav.contact' => 'Contact',
                'header.nav.searchToggle' => 'Open search',
                'header.nav.searchToggleSr' => 'Open search',
                'header.nav.searchPlaceholder' => 'Search services...',
                'header.nav.searchLabel' => 'Search services',
                'header.nav.language.es' => 'ES',
                'header.nav.language.en' => 'EN',
                'header.nav.languageSwitcher' => 'Change language',
                'header.nav.ariaMain' => 'Main menu',
                'header.nav.quote' => 'Request Quote',
                'footer.company' => 'Company',
                'footer.information' => 'Information',
                'footer.followUs' => 'Follow Us',
                'footer.contactUs' => 'Contact us',
                'footer.howWeWork' => 'How we work',
                'footer.terms' => 'Terms and conditions',
                'footer.privacy' => 'Privacy policy',
                'footer.rightsDefault' => '© %s Global Induprod International. All rights reserved.',
                'footer.rightsTrademark' => 'All trademarks belong to their respective owners.',
                'footer.scrollTop' => 'Scroll to top',
                'admin.panel.title' => 'Admin panel',
                'admin.login.title' => 'Admin panel - Sign in',
                'admin.login.heading' => 'Admin panel',
                'admin.login.username' => 'Username',
                'admin.login.password' => 'Password',
                'admin.login.submit' => 'Sign in',
                'admin.login.error.missing' => 'Both fields are required.',
                'admin.login.error.invalid' => 'Incorrect username or password.',
                'admin.login.error.general' => 'Sign-in failed. Please try again.',
                'admin.dashboard.welcome' => 'Welcome%s. Use the quick links to manage the content.',
                'admin.dashboard.shortcut.home' => 'Manage Home',
                'admin.dashboard.shortcut.about' => 'About section',
                'admin.dashboard.shortcut.services' => 'Services',
                'admin.dashboard.shortcut.contact' => 'Contact',
                'admin.dashboard.shortcut.header' => 'Header',
                'admin.dashboard.shortcut.footer' => 'Footer',
                'admin.dashboard.shortcut.data' => 'Admin data',
                'admin.dashboard.shortcut.caption' => 'Manage module',
                'admin.sidebar.dashboard' => 'Dashboard',
                'admin.sidebar.home' => 'Home',
                'admin.sidebar.about' => 'About',
                'admin.sidebar.services' => 'Services',
                'admin.sidebar.contact' => 'Contact',
                'admin.sidebar.header' => 'Header',
                'admin.sidebar.footer' => 'Footer',
                'admin.sidebar.data' => 'Admin data',
                'admin.sidebar.logout' => 'Sign out',
                'admin.sidebar.welcome' => 'Signed in as',
                'admin.sidebar.brand' => 'Administrator',
                'admin.sidebar.toggle' => 'Open menu',
                'admin.sidebar.ariaNav' => 'Admin navigation menu',
                'admin.notice.unsaved' => 'You have unsaved changes.',
                'admin.notice.saved' => 'Changes saved successfully.',
                'admin.error.db_connect' => 'Database connection error.',
                'admin.error.charset' => 'Unable to set connection charset.',
                'admin.home.title' => 'Home | Administration',
                'admin.home.header' => 'Home page management',
                'admin.notice.countersError' => 'Counters could not be loaded at this time.',
                'admin.common.totalLabel' => 'Total:',
                'admin.home.heroCardTitle' => 'Main carousel',
                'admin.home.heroCardDesc' => 'Manage the hero slides.',
                'admin.home.copyCardTitle' => 'Highlighted texts',
                'admin.home.copyCardDesc' => 'Edit section titles and paragraphs.',
                'admin.home.alliesCardTitle' => 'Strategic partners',
                'admin.home.alliesCardDesc' => 'Manage main and additional logos.',
                'admin.home.clientsCardTitle' => 'Featured clients',
                'admin.home.clientsCardDesc' => 'Upload logos and define display order.',
            ],
        ],
    ],
];
