<?php
return [
    'default' => 'globalinduprod',
    'tenants' => [
        'globalinduprod' => [
            'domains' => [
                'globalinduprod.com',
                'www.globalinduprod.com',
            ],
            'language_code' => 'es',
            'locale' => 'es_VE',
            'admin_db' => [
                'host' => 'localhost',
                'username' => 'u680460687_globalinduprod',
                'password' => 'B1S:N8:kW',
                'database' => 'u680460687_globalinduprod',
                'port' => 3306,
                'charset' => 'utf8mb4',
            ],
            'storage' => [
                'relative_root' => 'uploads',
            ],
            'labels' => [
                'tenant.name' => 'Global Induprod',
            ],
        ],
        'globalinduprodinternational' => [
            'domains' => [
                'globalinduprodinternational.com',
                'www.globalinduprodinternational.com',
            ],
            'language_code' => 'en',
            'locale' => 'en_US',
            'admin_db' => [
                'host' => 'localhost',
                'username' => 'u680460687_globaleeuu',
                'password' => 'n5h*&BBR1K@',
                'database' => 'u680460687_globaleeuu',
                'port' => 3306,
                'charset' => 'utf8mb4',
            ],
            'storage' => [
                'relative_root' => 'uploads/international',
            ],
            'labels' => [
                'tenant.name' => 'Global Induprod International',
                'header.nav.home' => 'Home',
                'header.nav.about' => 'About Us',
                'header.nav.services' => 'Services',
                'header.nav.contact' => 'Contact',
                'header.nav.searchToggle' => 'Open search',
                'header.nav.searchToggleSr' => 'Open search',
                'header.nav.searchPlaceholder' => 'Search services...',
                'header.nav.searchLabel' => 'Search services',
                'header.nav.language.es' => 'ES',
                'header.nav.language.en' => 'EN',
                'header.nav.languageSwitcher' => 'Change language',
                'header.nav.ariaMain' => 'Main menu',
                'header.nav.quote' => 'Request Quote',
                'footer.company' => 'Company',
                'footer.information' => 'Information',
                'footer.followUs' => 'Follow Us',
                'footer.contactUs' => 'Contact us',
                'footer.howWeWork' => 'How we work',
                'footer.terms' => 'Terms and conditions',
                'footer.privacy' => 'Privacy policy',
                'footer.rightsDefault' => '© %s Global Induprod International. All rights reserved.',
                'footer.rightsTrademark' => 'All trademarks belong to their respective owners.',
                'footer.scrollTop' => 'Scroll to top',
                'admin.panel.title' => 'Admin panel',
                'admin.login.title' => 'Admin panel - Sign in',
                'admin.login.heading' => 'Admin panel',
                'admin.login.username' => 'Username',
                'admin.login.password' => 'Password',
                'admin.login.submit' => 'Sign in',
                'admin.login.error.missing' => 'Both fields are required.',
                'admin.login.error.invalid' => 'Incorrect username or password.',
                'admin.login.error.general' => 'Sign-in failed. Please try again.',
                'admin.dashboard.welcome' => 'Welcome%s. Use the quick links to manage the content.',
                'admin.dashboard.shortcut.home' => 'Manage Home',
                'admin.dashboard.shortcut.about' => 'About section',
                'admin.dashboard.shortcut.services' => 'Services',
                'admin.dashboard.shortcut.contact' => 'Contact',
                'admin.dashboard.shortcut.header' => 'Header',
                'admin.dashboard.shortcut.footer' => 'Footer',
                'admin.dashboard.shortcut.data' => 'Admin data',
                'admin.dashboard.shortcut.caption' => 'Manage module',
                'admin.sidebar.dashboard' => 'Dashboard',
                'admin.sidebar.home' => 'Home',
                'admin.sidebar.about' => 'About',
                'admin.sidebar.services' => 'Services',
                'admin.sidebar.contact' => 'Contact',
                'admin.sidebar.header' => 'Header',
                'admin.sidebar.footer' => 'Footer',
                'admin.sidebar.data' => 'Admin data',
                'admin.sidebar.logout' => 'Sign out',
                'admin.sidebar.welcome' => 'Signed in as',
                'admin.sidebar.brand' => 'Administrator',
                'admin.sidebar.toggle' => 'Open menu',
                'admin.sidebar.ariaNav' => 'Admin navigation menu',
                'admin.notice.unsaved' => 'You have unsaved changes.',
                'admin.notice.saved' => 'Changes saved successfully.',
                'admin.error.db_connect' => 'Database connection error.',
                'admin.error.charset' => 'Unable to set connection charset.',
                'admin.home.title' => 'Home | Administration',
                'admin.home.header' => 'Home page management',
                'admin.notice.countersError' => 'Counters could not be loaded at this time.',
                'admin.common.totalLabel' => 'Total:',
                'admin.home.heroCardTitle' => 'Main carousel',
                'admin.home.heroCardDesc' => 'Manage the hero slides.',
                'admin.home.copyCardTitle' => 'Highlighted texts',
                'admin.home.copyCardDesc' => 'Edit section titles and paragraphs.',
                'admin.home.alliesCardTitle' => 'Strategic partners',
                'admin.home.alliesCardDesc' => 'Manage main and additional logos.',
                'admin.home.clientsCardTitle' => 'Featured clients',
                'admin.home.clientsCardDesc' => 'Upload logos and define display order.',
                'admin.contact.title' => 'Contact | Administration',
                'admin.contact.header' => 'Contact page content',
                'admin.contact.sectionHeading' => 'Contact page content',
                'admin.contact.defaults.heroKicker' => '24/7 support',
                'admin.contact.defaults.heroDescription' => 'Share part numbers, equipment models and logistics requirements. Our team replies with availability, lead times and compatible alternatives.',
                'admin.contact.defaults.phonePlaceholder' => '+1 305-000-0000',
                'admin.contact.defaults.emailSubject' => 'New inquiry from the website',
                'admin.contact.flash.saved' => 'Contact settings saved successfully.',
                'admin.contact.error.heroTitle' => 'Enter the hero headline.',
                'admin.contact.error.heroDescription' => 'Enter the hero description.',
                'admin.contact.error.content' => 'Provide the contact content.',
                'admin.contact.error.phonePlaceholder' => 'Enter the placeholder phone number.',
                'admin.contact.error.contactEmail' => 'Enter a valid recipient email address.',
                'admin.contact.error.smtpFromEmail' => 'Provide a valid sender email.',
                'admin.contact.error.emailSubject' => 'Enter the default message subject.',
                'admin.contact.error.save' => 'The contact settings could not be saved.',
                'admin.contact.form.heroTitle' => 'Hero headline (H1)',
                'admin.contact.form.heroKicker' => 'Hero eyebrow text',
                'admin.contact.form.heroDescription' => 'Hero description',
                'admin.contact.form.heroImage' => 'Hero background image',
                'admin.contact.form.heroImageAlt' => 'Current hero image',
                'admin.contact.form.removeHeroImage' => 'Remove current image',
                'admin.contact.form.currentPath' => 'Current path:',
                'admin.contact.form.contactContent' => 'Contact content (HTML)',
                'admin.contact.form.phonePlaceholder' => 'Placeholder phone example',
                'admin.contact.form.mapEmbed' => 'Google Maps location (URL or iframe)',
                'admin.contact.form.contactEmail' => 'Recipient email',
                'admin.contact.form.smtpLegend' => 'SMTP settings (PHPMailer)',
                'admin.contact.form.smtpHost' => 'SMTP server',
                'admin.contact.form.smtpPort' => 'Port',
                'admin.contact.form.smtpEncryption' => 'Encryption',
                'admin.contact.form.smtpEncryption.none' => 'No encryption',
                'admin.contact.form.smtpEncryption.tls' => 'TLS',
                'admin.contact.form.smtpEncryption.ssl' => 'SSL',
                'admin.contact.form.smtpAuth' => 'Use SMTP authentication',
                'admin.contact.form.smtpUsername' => 'SMTP user',
                'admin.contact.form.smtpPassword' => 'SMTP password',
                'admin.contact.form.smtpFromEmail' => 'Sender email',
                'admin.contact.form.smtpFromName' => 'Sender name',
                'admin.contact.form.emailSubject' => 'Default subject',
                'admin.contact.form.emailLogo' => 'Email template logo',
                'admin.contact.form.emailLogoAlt' => 'Current logo',
                'admin.contact.form.removeEmailLogo' => 'Remove current logo',
                'admin.contact.form.submit' => 'Save changes',
                'admin.contact.editor.heading.paragraph' => 'Paragraph',
                'admin.contact.editor.heading.h2' => 'Heading 2',
                'admin.contact.editor.heading.h3' => 'Heading 3',
                'admin.contact.editor.initError' => 'Could not initialize the editor:',
            ],
        ],
    ],
];
